# Generated by Django 3.2.16 on 2022-10-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docentes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
